// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quanlybanhang_nmcnpm.Database;

#nullable disable

namespace quanlybanhang_nmcnpm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517110141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Category", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhaCungCap");

                    b.HasData(
                        new
                        {
                            MaNhaCungCap = 1,
                            TenNCC = "Nha Cung Cap A"
                        },
                        new
                        {
                            MaNhaCungCap = 2,
                            TenNCC = "Nha Cung Cap B"
                        });

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Customer", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChiKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            DiaChiKH = "12 Le Loi, Da Nang",
                            Email = "kh.b@example.com",
                            NgayDangKy = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1995, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000002",
                            TenKH = "Tran Thi B"
                        },
                        new
                        {
                            MaKH = 2,
                            DiaChiKH = "99 Tran Hung Dao, Ho Chi Minh",
                            Email = "kh.c@example.com",
                            NgayDangKy = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1988, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000003",
                            TenKH = "Pham Van C"
                        });

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.InventoryReceipt", b =>
                {
                    b.Property<int>("MaPhieuNhapKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhapKho"));

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhapKho")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhapKho");

                    b.HasData(
                        new
                        {
                            MaPhieuNhapKho = 1,
                            MaNhaCungCap = 1,
                            MaNhanVien = 1,
                            NgayNhapKho = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 900000
                        });

                    b.ToTable("InventoryReceipts");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.InventoryReceiptDetail", b =>
                {
                    b.Property<int>("MaPhieuNhapKho")
                        .HasColumnType("int");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("DonGiaNhap")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhapKho", "MaHang");

                    b.HasIndex("MaHang");

                    b.HasData(
                        new
                        {
                            MaPhieuNhapKho = 1,
                            MaHang = 1,
                            DonGiaNhap = 90000,
                            SoLuongNhap = 10,
                            ThanhTien = 900000
                        });

                    b.ToTable("InventoryReceiptDetails");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Order", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaKH");

                    b.HasData(
                        new
                        {
                            MaDonHang = 1,
                            MaKH = 1,
                            MaNhanVien = 1,
                            NgayLap = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 1500000m
                        });

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.OrderDetail", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("MaDonHang", "MaHang");

                    b.HasIndex("MaHang");

                    b.HasData(
                        new
                        {
                            MaDonHang = 1,
                            MaHang = 1,
                            DonGiaBan = 1000000,
                            SoLuong = 1,
                            ThanhTien = 1000000
                        },
                        new
                        {
                            MaDonHang = 1,
                            MaHang = 2,
                            DonGiaBan = 500000,
                            SoLuong = 1,
                            ThanhTien = 500000
                        });

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Product", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHang");

                    b.HasIndex("MaNhaCungCap");

                    b.HasData(
                        new
                        {
                            MaHang = 1,
                            MaLoai = "PC",
                            MaNhaCungCap = 1,
                            SoLuongTon = 50,
                            TenHang = "Ban Phim Co"
                        },
                        new
                        {
                            MaHang = 2,
                            MaLoai = "ACC",
                            MaNhaCungCap = 2,
                            SoLuongTon = 40,
                            TenHang = "Chuot Khong Day"
                        });

                    b.ToTable("Products");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Role", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "NhanVien"
                        });

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.User", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("DiaChiKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaVaiTro");

                    b.HasData(
                        new
                        {
                            MaNhanVien = 1,
                            DiaChiKH = "1 Nguyen Trai, Ha Noi",
                            Email = "nv.a@example.com",
                            MaKH = 1,
                            MaVaiTro = 1,
                            NgayDangKy = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000001",
                            TenKH = "Nguyen Van A",
                            TenNV = "Nguyen Van A"
                        });

                    b.ToTable("Users");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.InventoryReceiptDetail", b =>
                {
                    b.HasOne("quanlybanhang_nmcnpm.Models.Product", "Product")
                        .WithMany("InventoryReceiptDetails")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("quanlybanhang_nmcnpm.Models.InventoryReceipt", "InventoryReceipt")
                        .WithMany("InventoryReceiptDetails")
                        .HasForeignKey("MaPhieuNhapKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Order", b =>
                {
                    b.HasOne("quanlybanhang_nmcnpm.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.OrderDetail", b =>
                {
                    b.HasOne("quanlybanhang_nmcnpm.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quanlybanhang_nmcnpm.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Product", b =>
                {
                    b.HasOne("quanlybanhang_nmcnpm.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.User", b =>
                {
                    b.HasOne("quanlybanhang_nmcnpm.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.InventoryReceipt", b =>
                {
                    b.Navigation("InventoryReceiptDetails");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Product", b =>
                {
                    b.Navigation("InventoryReceiptDetails");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("quanlybanhang_nmcnpm.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
